import { auth } from "@/auth";
import { Container, Section, Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { NavBar } from "./NavBar";
import ReactQueryProvider from "./QueryClientProvider";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ReactQueryProvider>
          <SessionProvider session={session}>
            <Theme appearance="dark" accentColor="red">
              <main>
                <Container height={"100vh"} size={{ sm: "2", md: "3" }}>
                  <NavBar />

                  <Section height={"100%"} px="2">
                    {children}
                  </Section>
                  <ToastContainer />
                </Container>
              </main>
            </Theme>
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
